service:
  name: todos

plugins: 
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1

functions: 
  createTodo:
    handler: src/functions/createTodo.handle
    events:
      - http:
          path: /createTodo/{user_id}
          method: POST
          cors: true
  getTodos:
    handler: src/functions/getTodos.handle
    events:
      - http:
          path: /getTodos/{user_id}
          method: GET
          cors: true


resources:
  Resources: 
    dbUsersTodos:
      Type: AWS::DynamoDB::Table

      Properties:
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: users_todos
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH